### ISSUE TITLE
Write a shell script to create a list of all the dependencies (current and latest version)...

### ISSUE THREAD

**Issue by Suvarchala-30** [Sopra-Banking-Software-Interns/auto-dependency-update#4]
...Create another shell script to update the outdated dependencies and create another list.

**Comment by CodePrakhar** [comment]
I am assuming a file containing json data 

{
    "@babel/generator": "7.18.2",
    "@babel/parser": "7.18.4",
    "@babel/types": "7.19.0",
    "chalk": "^4.1.2",
    "fs-extra": "^9.1.0",
    "globby": "^11.1.0",
    "into-stream": "^6.0.0",
    "is-core-module": "2.9.0",
    "minimist": "^1.2.6",
    "multistream": "^4.1.0",
    "pkg-fetch": "3.5.2",
    "prebuild-install": "7.1.1",
    "resolve": "^1.22.0",
    "stream-meter": "^1.0.4"
  }
  
  in this format 
  
  @Riyu44
